### ISSUE TITLE
Why it dont working the home menu

### ISSUE THREAD

**Issue by HumanoidSandvichDispenser** [minusArko/SustainableEats-App-Mockup#1]
Hello , please kindly fix this:

![image](https://github.com/minusArko/SustainableEats-App-Mockup/assets/25856867/decc557e-8373-48de-876b-ade23ef35dc4)
Home menu 

![image](https://github.com/minusArko/SustainableEats-App-Mockup/assets/25856867/922a907a-461b-4d3e-94d6-9c3d4410ecb0)

Settings gear icon

Please kindly fix , bless thank you 🙏

**Comment by CamHealy** [comment]
Looks like it's fixed
